// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgo9oxjaChm09Ee6WywNC8VQIIdMwuwY8',
    appId: '1:63599868692:web:834a5fbff3baf12dffe001',
    messagingSenderId: '63599868692',
    projectId: 'todoapp-nicholas',
    authDomain: 'todoapp-nicholas.firebaseapp.com',
    storageBucket: 'todoapp-nicholas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUj4Ummd0pLLL_1RYxWqQRsD6Rh8_iSc',
    appId: '1:63599868692:android:78bf90a74cc95ff7ffe001',
    messagingSenderId: '63599868692',
    projectId: 'todoapp-nicholas',
    storageBucket: 'todoapp-nicholas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNXR5XcTzzCIAOh18MKnsM19RRR4PTw8',
    appId: '1:63599868692:ios:47aad48df5e361b0ffe001',
    messagingSenderId: '63599868692',
    projectId: 'todoapp-nicholas',
    storageBucket: 'todoapp-nicholas.appspot.com',
    iosClientId: '63599868692-uii5qmg3rl8m9dceb026h4eec5qpooqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbNXR5XcTzzCIAOh18MKnsM19RRR4PTw8',
    appId: '1:63599868692:ios:47aad48df5e361b0ffe001',
    messagingSenderId: '63599868692',
    projectId: 'todoapp-nicholas',
    storageBucket: 'todoapp-nicholas.appspot.com',
    iosClientId: '63599868692-uii5qmg3rl8m9dceb026h4eec5qpooqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
